name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.0
          cache: true
          
      - name: Install dependencies
        run: |
          flutter pub get
          # The build_runner is essential for Boorusama's code generation
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK (Armv7a Only)
        run: |
          flutter build apk --release \
            --target-platform android-arm \
          # --split-per-abi \
            --dart-define-from-file env/dev.json \
            -t lib/main.dart

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Boorusama-Armv7a-Unsigned
          # Path for the specific armv7a build output
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
